=== monwe-jr/TrafficSim/Map.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="map">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="ArrayOfArrayOfSegment"/>
            </xs:sequence>
            <xs:attribute name="interCount" use="required" type="xs:nonNegativeInteger"/>
            <xs:attribute name="limit" use="required" type="xs:nonNegativeInteger" default="0"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="ArrayOfArrayOfSegment">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="ArrayOfSegment"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="ArrayOfSegment">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="Segment"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Segment">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="direction" type="Direction"/>
                <xs:element name="location" type="Point"/>
                <xs:element name="laneCount" type="xs:int"/>
                <xs:element name="segLength" type="xs:int"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="Direction">
        <xs:restriction base="xs:string">
            <xs:enumeration value="North"/>
            <xs:enumeration value="South"/>
            <xs:enumeration value="West"/>
            <xs:enumeration value="East"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="Point">
        <xs:sequence>
            <xs:element name="x" type="xs:int"/>
            <xs:element name="y" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== monwe-jr/TrafficSim/Map.xml
<?xml version="1.0"?>

<map xmlns:xsi="http://www.w3.org/2001/XMLSchema"
     xsi:schemaLocation="file://Map.xsd"
     interCount="" limit="" >

    <ArrayOfArrayOfSegment>
        <ArrayOfSegment>
            <Segment>
                <direction></direction>
                <location>
                    <x></x>
                    <y></y>
                </location>
                <laneCount></laneCount>
                <segLength></segLength>
            </Segment>
        </ArrayOfSegment>
    </ArrayOfArrayOfSegment>
</map>
